// <auto-generated />
using System;
using BookStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.Data.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    [Migration("20240518160856_AddMissingGenreAndRelationsToSeed")]
    partial class AddMissingGenreAndRelationsToSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 1
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 3
                        },
                        new
                        {
                            AuthorsId = 4,
                            BooksId = 4
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 5
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 6
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 7
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 8
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 9
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 10
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 11
                        },
                        new
                        {
                            AuthorsId = 6,
                            BooksId = 12
                        },
                        new
                        {
                            AuthorsId = 7,
                            BooksId = 13
                        },
                        new
                        {
                            AuthorsId = 7,
                            BooksId = 14
                        },
                        new
                        {
                            AuthorsId = 7,
                            BooksId = 15
                        },
                        new
                        {
                            AuthorsId = 7,
                            BooksId = 16
                        },
                        new
                        {
                            AuthorsId = 8,
                            BooksId = 17
                        },
                        new
                        {
                            AuthorsId = 8,
                            BooksId = 18
                        },
                        new
                        {
                            AuthorsId = 9,
                            BooksId = 19
                        },
                        new
                        {
                            AuthorsId = 10,
                            BooksId = 20
                        });
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("BookGenre");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 1,
                            GenresId = 8
                        },
                        new
                        {
                            BooksId = 2,
                            GenresId = 5
                        },
                        new
                        {
                            BooksId = 2,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 2,
                            GenresId = 13
                        },
                        new
                        {
                            BooksId = 3,
                            GenresId = 5
                        },
                        new
                        {
                            BooksId = 3,
                            GenresId = 11
                        },
                        new
                        {
                            BooksId = 3,
                            GenresId = 12
                        },
                        new
                        {
                            BooksId = 4,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 5,
                            GenresId = 7
                        },
                        new
                        {
                            BooksId = 5,
                            GenresId = 12
                        },
                        new
                        {
                            BooksId = 5,
                            GenresId = 13
                        },
                        new
                        {
                            BooksId = 6,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 7,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 8,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 9,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 10,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 11,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 12,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 13,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 14,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 15,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 16,
                            GenresId = 6
                        },
                        new
                        {
                            BooksId = 17,
                            GenresId = 14
                        },
                        new
                        {
                            BooksId = 17,
                            GenresId = 16
                        },
                        new
                        {
                            BooksId = 18,
                            GenresId = 14
                        },
                        new
                        {
                            BooksId = 18,
                            GenresId = 5
                        },
                        new
                        {
                            BooksId = 19,
                            GenresId = 14
                        },
                        new
                        {
                            BooksId = 19,
                            GenresId = 16
                        },
                        new
                        {
                            BooksId = 19,
                            GenresId = 8
                        },
                        new
                        {
                            BooksId = 20,
                            GenresId = 15
                        },
                        new
                        {
                            BooksId = 20,
                            GenresId = 16
                        },
                        new
                        {
                            BooksId = 20,
                            GenresId = 7
                        },
                        new
                        {
                            BooksId = 20,
                            GenresId = 5
                        });
                });

            modelBuilder.Entity("BookStore.Data.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Stephen Edwin King is an American author. Called the \"King of Horror\", he has also explored other genres, among them suspense, crime, science-fiction, fantasy and mystery. He has also written approximately 200 short stories, most of which have been published in collections.",
                            ImagePath = "/images/authors/stephenking-sm.jpg",
                            Name = "Stephen King"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Andrzej Sapkowski is a Polish fantasy writer, essayist, translator and a trained economist. He is best known for his six-volume series of books The Witcher, which revolves around the eponymous \"witcher,\" a monster-hunter, Geralt of Rivia.",
                            ImagePath = "/images/authors/Andrzej_Sapkowski.jpg",
                            Name = "Andrzej Sapkowski"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Jay Asher is an American writer and novelist. He is best known for writing the bestselling 2007 book Thirteen Reasons Why.",
                            ImagePath = "/images/authors/Jay_asher_2011.jpg",
                            Name = "Jay Asher"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Christie Golden is an American author. She has written many novels and several short stories in fantasy, horror and science fiction.",
                            ImagePath = "/images/authors/christie_golden.jpg",
                            Name = "Christie Golden"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ernest Christy Cline is an American science fiction novelist, slam poet, and screenwriter. He wrote the novels Ready Player One, Armada, and Ready Player Two and co-wrote the screenplay for the film adaptation of Ready Player One, directed by Steven Spielberg.",
                            Name = "Ernest Cline"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Joanne Rowling CH OBE FRSL, known by her pen name J. K. Rowling, is a British author and philanthropist. She wrote Harry Potter, a seven-volume fantasy series published from 1997 to 2007.",
                            ImagePath = "/images/authors/J.K.-Rowling-2021.jpg",
                            Name = "J.K Rowling"
                        },
                        new
                        {
                            Id = 7,
                            Description = "John Ronald Reuel Tolkien CBE FRSL was an English writer and philologist. He was the author of the high fantasy works The Hobbit and The Lord of the Rings. From 1925 to 1945, Tolkien was the Rawlinson and Bosworth Professor of Anglo-Saxon and a Fellow of Pembroke College, both at the University of Oxford.",
                            ImagePath = "/images/authors/tolkien.jpg",
                            Name = "J.R.R Tolkien"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Tatsuki Fujimoto is a Japanese manga artist, known for his works Fire Punch and Chainsaw Man.",
                            ImagePath = "/images/authors/Tatsuki Fujimoto.jpg",
                            Name = "Tatsuki Fujimoto"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Sui Ishida is a Japanese manga artist. He is popularly known for his dark fantasy manga series Tokyo Ghoul and Choujin X.",
                            ImagePath = "/images/authors/sui ishida.jpg",
                            Name = "Sui Ishida"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Asato Asato is a female Japanese novelist. The pen name Asato Asato is a combination of her real name and eighty-eight. .",
                            ImagePath = "/images/authors/Asato_Asato.jpg",
                            Name = "Asato Asato"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("SoldCopies")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("YearOfRelease")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The story follows the experiences of seven children as they are terrorized by an evil entity that exploits the fears of its victims to disguise itself",
                            Discount = 0,
                            ImagePath = "/images/books/it cover.jpg",
                            IsActive = true,
                            PageCount = 1138,
                            Price = 12.0,
                            PublisherId = 1,
                            SoldCopies = 0,
                            Title = "It",
                            YearOfRelease = 1986
                        },
                        new
                        {
                            Id = 2,
                            Description = "Geralt the Witcher—revered and hated—holds the line against the monsters plaguing humanity in this collection of adventures, the first chapter in Andrzej Sapkowski’s groundbreaking epic fantasy series that inspired the hit Netflix show and the blockbuster video games.",
                            Discount = 0,
                            ImagePath = "/images/books/witcher saga cover.jpg",
                            IsActive = true,
                            PageCount = 2000,
                            Price = 70.650000000000006,
                            PublisherId = 2,
                            SoldCopies = 0,
                            Title = "The Witcher Saga",
                            YearOfRelease = 2020
                        },
                        new
                        {
                            Id = 3,
                            Description = "Thirteen Reasons Why is a young adult novel written by Jay Asher in 2007, which follows the story of Hannah Baker, a high school freshman, and the thirteen reasons why she has died by suicide.",
                            Discount = 0,
                            ImagePath = "/images/books/13 reasons why cover.jpg",
                            IsActive = true,
                            PageCount = 320,
                            Price = 30.0,
                            PublisherId = 3,
                            SoldCopies = 0,
                            Title = "13 Reasons Why",
                            YearOfRelease = 2007
                        },
                        new
                        {
                            Id = 4,
                            Description = "Arthas: Rise of the Lich King is a Warcraft novel by Christie Golden, who is the author of multiple Star Trek and other Warcraft novels. The novel dealing with the progression of Arthas from Prince to the Lich King, was released on April 21, 2009.",
                            Discount = 0,
                            ImagePath = "/images/books/wow arthas cover.jpg",
                            IsActive = true,
                            PageCount = 416,
                            Price = 20.0,
                            PublisherId = 4,
                            SoldCopies = 0,
                            Title = "World of Warcraft: Arthas: Rise of the Lich King",
                            YearOfRelease = 2007
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ready Player One is a 2011 science fiction novel, and the debut novel of American author Ernest Cline. The story, set in a dystopia in 2045, follows protagonist Wade Watts on his search for an Easter egg in a worldwide virtual reality game, the discovery of which would lead him to inherit the game creator's fortune.",
                            Discount = 0,
                            ImagePath = "/images/books/ready player one cover.jpg",
                            IsActive = true,
                            PageCount = 384,
                            Price = 25.649999999999999,
                            PublisherId = 5,
                            SoldCopies = 0,
                            Title = "Ready Player One",
                            YearOfRelease = 2011
                        },
                        new
                        {
                            Id = 6,
                            Description = "Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school and with the help of his friends, Ron Weasley and Hermione Granger, he faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",
                            Discount = 0,
                            ImagePath = "/images/books/harry_philosopher-stone.jpg",
                            IsActive = true,
                            PageCount = 223,
                            Price = 25.0,
                            PublisherId = 6,
                            SoldCopies = 0,
                            Title = "Harry Potter and the Philosopher's Stone",
                            YearOfRelease = 1997
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ever since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange impish creature who says that if Harry returns to Hogwarts, disaster will strike.\r\n",
                            Discount = 0,
                            ImagePath = "/images/books/Harry Potter and the Chamber of Secrets.jpg",
                            IsActive = true,
                            PageCount = 352,
                            Price = 25.0,
                            PublisherId = 6,
                            SoldCopies = 0,
                            Title = "Harry Potter and the Chamber of Secrets",
                            YearOfRelease = 1998
                        },
                        new
                        {
                            Id = 8,
                            Description = "Ever since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange impish creature who says that if Harry returns to Hogwarts, disaster will strike.",
                            Discount = 0,
                            ImagePath = "/images/books/Harry Potter and the Prisoner of Azkaban.jpg",
                            IsActive = true,
                            PageCount = 435,
                            Price = 25.0,
                            PublisherId = 6,
                            SoldCopies = 0,
                            Title = "Harry Potter and the Prisoner of Azkaban",
                            YearOfRelease = 1999
                        },
                        new
                        {
                            Id = 9,
                            Description = "It is the summer holidays and soon Harry Potter will be starting his fourth year at Hogwarts School of Witchcraft and Wizardry. Harry is counting the days: there are new spells to be learnt, more Quidditch to be played, and Hogwarts castle to continue exploring.",
                            Discount = 0,
                            ImagePath = "/images/books/Goblet of Fire.jpg",
                            IsActive = true,
                            PageCount = 734,
                            Price = 25.0,
                            PublisherId = 6,
                            SoldCopies = 0,
                            Title = "Harry Potter and the Goblet of Fire",
                            YearOfRelease = 2000
                        },
                        new
                        {
                            Id = 10,
                            Description = "Harry Potter is about to start his fifth year at Hogwarts School of Witchcraft and Wizardry. Unlike most schoolboys, Harry never enjoys his summer holidays, but this summer is even worse than usual. The Dursleys, of course, are making his life a misery, but even his best friends, Ron and Hermione, seem to be neglecting him.",
                            Discount = 0,
                            ImagePath = "/images/books/Order of Phoenix.jpg",
                            IsActive = true,
                            PageCount = 912,
                            Price = 25.0,
                            PublisherId = 6,
                            SoldCopies = 0,
                            Title = "Harry Potter and the Order of the Phoenix",
                            YearOfRelease = 2003
                        },
                        new
                        {
                            Id = 11,
                            Description = "It is the middle of the summer, but there is an unseasonal mist pressing against the windowpanes. Harry Potter is waiting nervously in his bedroom at the Dursleys' house in Privet Drive for a visit from Professor Dumbledore himself. One of the last times he saw the Headmaster, he was in a fierce one-to-one duel with Lord Voldemort, and Harry can't quite believe that Professor Dumbledore will actually appear at the Dursleys' of all places. Why is the Professor coming to visit him now? What is it that cannot wait until Harry returns to Hogwarts in a few weeks' time? Harry's sixth year at Hogwarts has already got off to an unusual start, as the worlds of Muggle and magic start to intertwine.",
                            Discount = 0,
                            ImagePath = "/images/books/Half-Blood Prince.jpg",
                            IsActive = true,
                            PageCount = 652,
                            Price = 25.0,
                            PublisherId = 6,
                            SoldCopies = 0,
                            Title = "Harry Potter and the Half-Blood Prince",
                            YearOfRelease = 2005
                        },
                        new
                        {
                            Id = 12,
                            Description = "Harry has been burdened with a dark, dangerous and seemingly impossible task: that of locating and destroying Voldemort's remaining Horcruxes. Never has Harry felt so alone, or faced a future so full of shadows. But Harry must somehow find within himself the strength to complete the task he has been given. He must leave the warmth, safety and companionship of The Burrow and follow without fear or hesitation the inexorable path laid out for him...In this final, seventh installment of the Harry Potter series, J.K. Rowling unveils in spectacular fashion the answers to the many questions that have been so eagerly awaited.",
                            Discount = 0,
                            ImagePath = "/images/books/Deathly Hallows.jpg",
                            IsActive = true,
                            PageCount = 759,
                            Price = 25.0,
                            PublisherId = 6,
                            SoldCopies = 0,
                            Title = "Harry Potter and the Deathly Hallows",
                            YearOfRelease = 2007
                        },
                        new
                        {
                            Id = 13,
                            Description = "In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort.\r\nWritten for J.R.R. Tolkien’s own children, The Hobbit met with instant critical acclaim when it was first published in 1937. Now recognized as a timeless classic, this introduction to the hobbit Bilbo Baggins, the wizard Gandalf, Gollum, and the spectacular world of Middle-earth recounts of the adventures of a reluctant hero, a powerful and dangerous ring, and the cruel dragon Smaug the Magnificent. The text in this 372-page paperback edition is based on that first published in Great Britain by Collins Modern Classics (1998), and includes a note on the text by Douglas A. Anderson (2001).",
                            Discount = 0,
                            ImagePath = "/images/books/the hobbit.jpg",
                            IsActive = true,
                            PageCount = 366,
                            Price = 25.0,
                            PublisherId = 7,
                            SoldCopies = 0,
                            Title = "The Hobbit",
                            YearOfRelease = 1937
                        },
                        new
                        {
                            Id = 14,
                            Description = "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them.\r\n\r\nIn ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit.\r\n\r\nIn a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.",
                            Discount = 0,
                            ImagePath = "/images/books/The Fellowship of the Ring.jpg",
                            IsActive = true,
                            PageCount = 432,
                            Price = 25.0,
                            PublisherId = 7,
                            SoldCopies = 0,
                            Title = "The Fellowship of the Ring",
                            YearOfRelease = 1954
                        },
                        new
                        {
                            Id = 15,
                            Description = "Begin your journey into Middle-earth.\r\n\r\nThe inspiration for the upcoming original series on Prime Video, The Lord of the Rings: The Rings of Power.\r\n\r\nThe Two Towers is the second part of J.R.R. Tolkien’s epic adventure The Lord of the Rings.\r\n\r\nOne Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them.\r\n\r\nFrodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go.",
                            Discount = 0,
                            ImagePath = "/images/books/the two towers.jpg",
                            IsActive = true,
                            PageCount = 432,
                            Price = 25.0,
                            PublisherId = 7,
                            SoldCopies = 0,
                            Title = "The Two Towers",
                            YearOfRelease = 1954
                        },
                        new
                        {
                            Id = 16,
                            Description = "Begin your journey into Middle-earth.\r\n\r\nThe inspiration for the upcoming original series on Prime Video, The Lord of the Rings: The Rings of Power.\r\n\r\nThe Return of the King is the third part of J.R.R. Tolkien’s epic adventure The Lord of the Rings.\r\n\r\nOne Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them.\r\n\r\nThe Dark Lord has risen, and as he unleashes hordes of Orcs to conquer all Middle-earth, Frodo and Sam struggle deep into his realm in Mordor.\r\n\r\nTo defeat Sauron, the One Ring must be destroyed in the fires of Mount Doom. But the way is impossibly hard, and Frodo is weakening. The Ring corrupts all who bear it and Frodo’s time is running out.\r\n\r\nWill Sam and Frodo succeed, or will the Dark Lord rule Middle-earth once more?",
                            Discount = 0,
                            ImagePath = "/images/books/the return of the king.jpg",
                            IsActive = true,
                            PageCount = 432,
                            Price = 25.0,
                            PublisherId = 7,
                            SoldCopies = 0,
                            Title = "The Return of the King",
                            YearOfRelease = 1955
                        },
                        new
                        {
                            Id = 17,
                            Description = "Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts. Using his pet devil Pochita as a weapon, he is ready to do anything for a bit of cash.\r\n\r\nUnfortunately, he has outlived his usefulness and is murdered by a devil in contract with the yakuza. However, in an unexpected turn of events, Pochita merges with Denji's dead body and grants him the powers of a chainsaw devil. Now able to transform parts of his body into chainsaws, a revived Denji uses his new abilities to quickly and brutally dispatch his enemies. Catching the eye of the official devil hunters who arrive at the scene, he is offered work at the Public Safety Bureau as one of them. Now with the means to face even the toughest of enemies, Denji will stop at nothing to achieve his simple teenage dreams.",
                            Discount = 0,
                            ImagePath = "/images/books/chainsawman-collection.jpg",
                            IsActive = true,
                            PageCount = 2109,
                            Price = 75.0,
                            PublisherId = 8,
                            SoldCopies = 0,
                            Title = "Chainsaw Man Box Set",
                            YearOfRelease = 2023
                        },
                        new
                        {
                            Id = 18,
                            Description = "Suffering from a terminal illness, Yuuta's mother asks him to film her last moments, which he does. From her radiant smile when she is with her family to the times when sickness ravages her body in the hospital, he records hours upon hours of footage. After her passing, Yuuta compiles her life into a movie to screen at his school, deciding to add a bit of fantasy to the ending of his film, Dead Explosion Mother, with a literal explosion!\r\n\r\nFollowing the backlash caused by his supposedly tone-deaf portrayal of his mother's death, Yuuta trudges to the hospital roof to take his own life—but there, he meets a girl named Eri. Captivated by his film, Eri requests Yuuta to make a new one that will blow the previous out of the water and prove his critics wrong. The movie they set out to make will stand apart by blurring the line between fact and fiction. And of course, it wouldn't be a Yuuta film if it didn't have his personal flavor—just a dash of fantasy.",
                            Discount = 0,
                            ImagePath = "/images/books/goodbye eri.jpg",
                            IsActive = true,
                            PageCount = 208,
                            Price = 26.989999999999998,
                            PublisherId = 8,
                            SoldCopies = 0,
                            Title = "Goodbye Eri",
                            YearOfRelease = 2022
                        },
                        new
                        {
                            Id = 19,
                            Description = "Ghouls live among us, the same as normal people in every way-except for their craving for human flesh.\r\n\r\nA box set that includes all fourteen volumes of the original Tokyo Ghoul series. Includes an exclusive double-sided poster.\r\n\r\nKen Kaneki is an ordinary college student until a violent encounter turns him into the first half-human, half-Ghoul hybrid. Trapped between two worlds, he must survive Ghoul turf wars, learn more about Ghoul society and master his new powers.",
                            Discount = 0,
                            ImagePath = "/images/books/tokyo ghoul box set.jpg",
                            IsActive = true,
                            PageCount = 2904,
                            Price = 115.0,
                            PublisherId = 8,
                            SoldCopies = 0,
                            Title = "Tokyo Ghoul Box Set",
                            YearOfRelease = 2018
                        },
                        new
                        {
                            Id = 20,
                            Description = "Nine years ago, the Empire of Giad declared war on all neighboring countries using an army of autonomous drones known as the Legion. Threatened by the soulless killing machines, the Republic of San Magnolia, home to the silver-haired Alba race, evacuated its citizens inside 85 districts and developed supposedly unmanned drones known as Juggernauts to counter the Legion. Even after years of war, the Republic boasts that they have suffered zero casualties. However, the battlefield bathed in crimson recites a different melody...\r\n\r\nThe hand dealt to the Colorata people—a minority forced into living in the \"nonexistent\" 86th district—is one of utter contempt and scorn. Looked upon as human filth, they are ordered to pilot the Juggernauts as Processors under the command of Republican Handlers.\r\n\r\nVladilena Milizé, a republican soldier with a strong sense of justice, detests the way her countrymen treat the 86. When she is assigned to the Spearhead Squadron as their handler, she meets a group of oddballs and eventually grows attached to them—particularly their captain, Shinei Nouzen, a boy with a pure sense of purpose and resolve. However, the path they walk is one riddled with death, and growing close to an 86 may have just set Vladilena down a path of despair..",
                            Discount = 0,
                            ImagePath = "/images/books/86 vol 1.jpg",
                            IsActive = true,
                            PageCount = 309,
                            Price = 16.989999999999998,
                            PublisherId = 8,
                            SoldCopies = 0,
                            Title = "86 Vol. 1",
                            YearOfRelease = 2017
                        });
                });

            modelBuilder.Entity("BookStore.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Satire"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Poetry"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 10,
                            Name = "History"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Manga"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Light-Novel"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Action"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BookStore.Data.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Simon & Schuster"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hachette Book Group"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RazorBill"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pocket Books"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ernest Cline"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bloomsbury"
                        },
                        new
                        {
                            Id = 7,
                            Name = "George Allen & Unwin"
                        },
                        new
                        {
                            Id = 8,
                            Name = "VIZ Media"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BookStore.Data.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("BookStore.Data.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Data.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("BookStore.Data.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Data.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Models.Book", b =>
                {
                    b.HasOne("BookStore.Data.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BookStore.Data.Models.Order", b =>
                {
                    b.HasOne("BookStore.Data.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookStore.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
